version: "3"
services:
  backend:
    image: jandve/examen-final
    depends_on:
      - db
    container_name: backend
    ports:
      - "3000:3000"
    expose:
      - 3000
  db:
    image: postgres
    restart: always
    container_name: database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=module_4_db
    expose:
      - 5432
